spring:
  application:
    name: location_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://220.73.19.191:5432/dongajul
    username: test
    password: test
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
# kafka 설정
  cloud:
    function:
      definition: kafkaConsumer
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
          kafkaConsumer-in-0:
            consumer:
              configuration:
                key:
                  deserializer: org.apache.kafka.common.serialization.StringDeserializer
        binder:
          brokers: 220.73.19.191:9092
      bindings:
        producer-out-0:
          destination: testTopic # topic
          contentType: application/json
        kafkaConsumer-in-0:
          destination: testTopic  # topic