spring:
  application:
    name: location_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://220.73.19.191:5432/dongajul
    username: test
    password: test
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
# kafka 설정
  cloud:
    stream:
      kafka:
        binder:
          brokers: 220.73.19.191:9092
      bindings:
        input-in-0:                                   # Consumer 클래스의 메소드명으로 기본 바인딩이 생긴다
          destination: toilet-registration-approved   # topic 이름
    function:
      definition: input;inputAsync                    # 사용하고 싶은 binding이 여러개일 경우 ;으로 구분하여 나열한다