spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:location;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10