server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: info_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://220.73.19.191:5432/dongajul
    username: 
    password: 

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
