spring:
  cloud:
    function:
      definition: kafkaConsumer
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
          kafkaConsumer-in-0:
            consumer:
              configuration:
                key:
                  deserializer: org.apache.kafka.common.serialization.StringDeserializer
        binder:
          brokers: 220.73.19.191:9092
      bindings:
        producer-out-0:
          destination: testTopic
          contentType: application/json
        kafkaConsumer-in-0:
          destination: testTopic

  application:
    name: review_service
  datasource:
    url: jdbc:postgresql://220.73.19.191:5432/dongajul
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10

server:
  port: 8085

