spring:
  application:
    name: review_service
  datasource:
    url: jdbc:postgresql://220.73.19.191:5432/dongajul
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10

server:
  port: 8085

